akka {
  loglevel = "INFO"
  
  actor {
    provider = "local"
  }
  
  http {
    server {
      idle-timeout = 60s
      request-timeout = 20s
      bind-timeout = 1s
    }
    
    client {
      connecting-timeout = 10s
    }
  }
}
